name: Documentation
description: Request documentation improvements or report documentation issues
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve Qurious documentation! Whether it's fixing typos, clarifying concepts, or adding new guides.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this? If you select "Other", please specify in Additional Context.
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear documentation
        - Typo/grammar fix
        - New guide/tutorial request
        - API documentation
        - Code comments
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation located or where should it be added?
      placeholder: |
        - File path: e.g., README.md, CONTRIBUTING.md, apps/web/README.md
        - URL: e.g., https://github.com/QuriousAI/qurious/...
        - Section: e.g., "Getting Started" section
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Current Issue
      description: What's wrong or missing in the current documentation?
      placeholder: Describe the problem with the current documentation...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Provide your suggested changes, additions, or improvements.
        For minor changes, you can include the exact text you'd like to see.
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      placeholder: |
        - New contributors
        - End users
        - Developers
        - Researchers
        - System administrators
        - etc.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or references
      placeholder: Links to similar documentation, examples from other projects, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this documentation issue hasn't been reported before
          required: true
        - label: I am willing to submit a PR to fix this documentation issue (optional)
          required: false