name: Feature Request
description: Suggest a new feature or enhancement for Qurious
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your input to make Qurious better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Other approaches you've thought about...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Feature Area
      description: Which area of Qurious would this feature affect? If you select "Other", please specify in Additional Context.
      options:
        - Search functionality
        - Paper chat/Q&A
        - Mobile App
        - Collections/Lists
        - Annotations/Notes
        - User interface
        - Browser extension
        - API
        - Authentication
        - Performance
        - Integrations
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        As a [type of user]...
        I want to [do something]...
        So that [achieve goal]...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other applications
      placeholder: Drag and drop images here or paste URLs to examples
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested before
          required: true
        - label: This feature aligns with Qurious's mission as an AI-powered research assistant
          required: true
        - label: I am willing to contribute to implementing this feature (optional)
          required: false